config/routes.rb
Games::Application.routes.draw do
  resources :mlb_standings

  resources :nba_playoff_scores

  resources :nba_playoff_bets
  get '/nbaPlayoffs' => 'nba_playoff_bets#allusers'
  get '/nbaPlayoffBets' => 'nba_playoff_bets#index'
  post '/nba_playoff_bets_save' => 'nba_playoff_bets#bulksave'

  resources :nba_playoff_matchups
  get 'nba_playoff_matchups/:id/winner' => 'nba_playoff_matchups#setwinner'
  post 'nba_playoff_matchups/:id/winner' => 'nba_playoff_matchups#updatewinner'

  resources :nba_teams

  resources :mlb_win_bets
  post '/mlb_win_bets_save' => 'mlb_win_bets#bulksave'
  get '/mlbOverUnders' => 'mlb_win_bets#allusers'
  get '/mlbOverUnderBets' => 'mlb_win_bets#index'

  resources :mlb_wins

  resources :mlb_teams

  resources :users
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get '/editProfile' => 'users#editprofile'
  get '/myGames' => 'users#mygames', :as => 'my_games'
  
  resources :sessions
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => 'sessions#new'

end

app/models/mlb_standing.rb
class MlbStanding < ActiveRecord::Base
  belongs_to :mlb_team
  attr_accessible :losses, :wins, :year

  # returns the number of projected wins based on a 162-game season
  def projected_wins
    games = self.wins + self.losses
    return games > 0 ? ((self.wins / games.to_f) * 162).round : 0
  end

  # returns the number of projected losses based on a 162-game season
  def projected_losses
  	return 162 - self.projected_wins
  end

  # returns the projected result [over/under/push], based on the specified line
  def projected_result(line)
  	wins = self.projected_wins
    if wins < line
      return "Under"
    elsif wins > line
      return "Over"
    else
      return "Push"
    end
  end

  # returns the projected offset between the specified line and the projected wins
  def projected_offset(line)
    proj_result = self.projected_result(line)
    if proj_result == "Over"
      return "+" + (self.projected_wins - line).to_s
    elsif proj_result == "Under"
      return "-" + (line - self.projected_wins).to_s
    else
      return ""
    end
  end
end

app/controllers/mlb_standings_controller.rb
class MlbStandingsController < ApplicationController
  # GET /mlb_standings
  # GET /mlb_standings.json
  def index
    @mlb_standings = MlbStanding.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mlb_standings }
    end
  end

  # GET /mlb_standings/1
  # GET /mlb_standings/1.json
  def show
    @mlb_standing = MlbStanding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mlb_standing }
    end
  end

  # GET /mlb_standings/new
  # GET /mlb_standings/new.json
  def new
    @mlb_standing = MlbStanding.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mlb_standing }
    end
  end

  # GET /mlb_standings/1/edit
  def edit
    @mlb_standing = MlbStanding.find(params[:id])
  end

  # POST /mlb_standings
  # POST /mlb_standings.json
  def create
    @mlb_standing = MlbStanding.new(params[:mlb_standing])

    respond_to do |format|
      if @mlb_standing.save
        format.html { redirect_to @mlb_standing, notice: 'Mlb standing was successfully created.' }
        format.json { render json: @mlb_standing, status: :created, location: @mlb_standing }
      else
        format.html { render action: "new" }
        format.json { render json: @mlb_standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mlb_standings/1
  # PUT /mlb_standings/1.json
  def update
    @mlb_standing = MlbStanding.find(params[:id])

    respond_to do |format|
      if @mlb_standing.update_attributes(params[:mlb_standing])
        format.html { redirect_to @mlb_standing, notice: 'Mlb standing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mlb_standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mlb_standings/1
  # DELETE /mlb_standings/1.json
  def destroy
    @mlb_standing = MlbStanding.find(params[:id])
    @mlb_standing.destroy

    respond_to do |format|
      format.html { redirect_to mlb_standings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mlb_standings_helper.rb
module MlbStandingsHelper
end

app/views/mlb_standings/_form.html.erb
<%= form_for(@mlb_standing) do |f| %>
  <% if @mlb_standing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mlb_standing.errors.count, "error") %> prohibited this mlb_standing from being saved:</h2>

      <ul>
      <% @mlb_standing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :mlb_team %><br />
    <%= f.text_field :mlb_team %>
  </div>
  <div class="field">
    <%= f.label :wins %><br />
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :losses %><br />
    <%= f.number_field :losses %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mlb_standings/edit.html.erb
<h1>Editing mlb_standing</h1>

<%= render 'form' %>

<%= link_to 'Show', @mlb_standing %> |
<%= link_to 'Back', mlb_standings_path %>

app/views/mlb_standings/index.html.erb
<h1>Listing mlb_standings</h1>

<table>
  <tr>
    <th>Year</th>
    <th>Mlb team</th>
    <th>Wins</th>
    <th>Losses</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mlb_standings.each do |mlb_standing| %>
  <tr>
    <td><%= mlb_standing.year %></td>
    <td><%= mlb_standing.mlb_team %></td>
    <td><%= mlb_standing.wins %></td>
    <td><%= mlb_standing.losses %></td>
    <td><%= link_to 'Show', mlb_standing %></td>
    <td><%= link_to 'Edit', edit_mlb_standing_path(mlb_standing) %></td>
    <td><%= link_to 'Destroy', mlb_standing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mlb standing', new_mlb_standing_path %>

app/views/mlb_standings/new.html.erb
<h1>New mlb_standing</h1>

<%= render 'form' %>

<%= link_to 'Back', mlb_standings_path %>

app/views/mlb_standings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @mlb_standing.year %>
</p>

<p>
  <b>Mlb team:</b>
  <%= @mlb_standing.mlb_team %>
</p>

<p>
  <b>Wins:</b>
  <%= @mlb_standing.wins %>
</p>

<p>
  <b>Losses:</b>
  <%= @mlb_standing.losses %>
</p>


<%= link_to 'Edit', edit_mlb_standing_path(@mlb_standing) %> |
<%= link_to 'Back', mlb_standings_path %>