config/routes.rb
Games::Application.routes.draw do
  resources :mlb_standings

  resources :nba_playoff_scores

  resources :nba_playoff_bets
  get '/nbaPlayoffs' => 'nba_playoff_bets#allusers'
  get '/nbaPlayoffBets' => 'nba_playoff_bets#index'
  post '/nba_playoff_bets_save' => 'nba_playoff_bets#bulksave'

  resources :nba_playoff_matchups
  get 'nba_playoff_matchups/:id/winner' => 'nba_playoff_matchups#setwinner'
  post 'nba_playoff_matchups/:id/winner' => 'nba_playoff_matchups#updatewinner'

  resources :nba_teams

  resources :mlb_win_bets
  post '/mlb_win_bets_save' => 'mlb_win_bets#bulksave'
  get '/mlbOverUnders' => 'mlb_win_bets#allusers'
  get '/mlbOverUnderBets' => 'mlb_win_bets#index'

  resources :mlb_wins

  resources :mlb_teams

  resources :users
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get '/editProfile' => 'users#editprofile'
  get '/myGames' => 'users#mygames', :as => 'my_games'
  
  resources :sessions
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => 'sessions#new'

end

app/models/nba_team.rb
class NbaTeam < ActiveRecord::Base
  attr_accessible :abbreviation, :city, :division, :league, :name
end

app/controllers/nba_teams_controller.rb
class NbaTeamsController < ApplicationController
  # GET /nba_teams
  # GET /nba_teams.json
  def index
    @nba_teams = NbaTeam.order(:league, :division, :abbreviation).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nba_teams }
    end
  end

  # GET /nba_teams/1
  # GET /nba_teams/1.json
  def show
    @nba_team = NbaTeam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nba_team }
    end
  end

  # GET /nba_teams/new
  # GET /nba_teams/new.json
  def new
    @nba_team = NbaTeam.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nba_team }
    end
  end

  # GET /nba_teams/1/edit
  def edit
    @nba_team = NbaTeam.find(params[:id])
  end

  # POST /nba_teams
  # POST /nba_teams.json
  def create
    @nba_team = NbaTeam.new(params[:nba_team])

    respond_to do |format|
      if @nba_team.save
        format.html { redirect_to '/nba_teams', notice: 'NBA team was successfully created.' }
        format.json { render json: @nba_team, status: :created, location: @nba_team }
      else
        format.html { render action: "new" }
        format.json { render json: @nba_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nba_teams/1
  # PUT /nba_teams/1.json
  def update
    @nba_team = NbaTeam.find(params[:id])

    respond_to do |format|
      if @nba_team.update_attributes(params[:nba_team])
        format.html { redirect_to @nba_team, notice: 'Nba team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nba_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nba_teams/1
  # DELETE /nba_teams/1.json
  def destroy
    @nba_team = NbaTeam.find(params[:id])
    @nba_team.destroy

    respond_to do |format|
      format.html { redirect_to nba_teams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/nba_teams_helper.rb
module NbaTeamsHelper
end

app/views/nba_teams/_form.html.erb
<%= form_for(@nba_team) do |f| %>
  <% if @nba_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nba_team.errors.count, "error") %> prohibited this nba_team from being saved:</h2>

      <ul>
      <% @nba_team.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :division %><br />
    <%= f.text_field :division %>
  </div>
  <div class="field">
    <%= f.label :league %><br />
    <%= f.text_field :league %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nba_teams/edit.html.erb
<%= navigationBar(NavigationHelper::ADMIN_NBA_TEAMS_BUTTON) %>

<div class='row-fluid'><div class='span12 center'>

<%= showNoticeAsAlert(notice) %>

<h3>Edit New NBA Team</h3>

<%= render 'form' %>

<%= link_to 'Show', @nba_team %> |
<%= link_to 'Back', nba_teams_path %>
<br/><br/>
</div></div>

app/views/nba_teams/index.html.erb
<%= navigationBar(NavigationHelper::ADMIN_NBA_TEAMS_BUTTON) %>

<div class='row-fluid'><div class='span12 center'>
<h3>Manage NBA Teams</h3>

<%= showNoticeAsAlert(notice) %>

<%= link_to 'Create NBA team', new_nba_team_path, class: 'btn' %><br/><br/>

<table class='table table-striped table-bordered table-condensed center'>
  <thead><tr>
    <th>ID</th>
    <th>City</th>
    <th>Name</th>
    <th>Abbreviation</th>
    <th>League</th>
    <th>Division</th>
    <th></th>
    <th></th>
    <th></th>
  </tr></thead>

<% @nba_teams.each do |nba_team| %>
  <tr>
    <td><%= nba_team.id %></td>
    <td><%= nba_team.city %></td>
    <td><%= nba_team.name %></td>
    <td><%= nba_team.abbreviation %></td>
    <td><%= nba_team.league %></td>
    <td><%= nba_team.division %></td>
    <td><%= link_to 'Show', nba_team %></td>
    <td><%= link_to 'Edit', edit_nba_team_path(nba_team) %></td>
    <td><%= link_to 'Destroy', nba_team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Create NBA team', new_nba_team_path, class: 'btn' %>
<br/><br/>
</div></div>

app/views/nba_teams/new.html.erb
<%= navigationBar(NavigationHelper::ADMIN_NBA_TEAMS_BUTTON) %>

<div class='row-fluid'><div class='span12 center'>

<%= showNoticeAsAlert(notice) %>

<h3>Create New NBA Team</h3>

<%= render 'form' %>

<%= link_to 'Back', nba_teams_path %>
<br/>
</div></div>

app/views/nba_teams/show.html.erb
<%= navigationBar(NavigationHelper::ADMIN_NBA_TEAMS_BUTTON) %>

<div class='row-fluid'><div class='span12 center'>

<%= showNoticeAsAlert(notice) %>

<p>
  <b>City:</b>
  <%= @nba_team.city %>
</p>

<p>
  <b>Name:</b>
  <%= @nba_team.name %>
</p>

<p>
  <b>Abbreviation:</b>
  <%= @nba_team.abbreviation %>
</p>

<p>
  <b>Division:</b>
  <%= @nba_team.division %>
</p>

<p>
  <b>League:</b>
  <%= @nba_team.league %>
</p>


<%= link_to 'Edit', edit_nba_team_path(@nba_team) %> |
<%= link_to 'Back', nba_teams_path %>

</div></div>