config/routes.rb
Games::Application.routes.draw do
  resources :mlb_standings

  resources :nba_playoff_scores

  resources :nba_playoff_bets
  get '/nbaPlayoffs' => 'nba_playoff_bets#allusers'
  get '/nbaPlayoffBets' => 'nba_playoff_bets#index'
  post '/nba_playoff_bets_save' => 'nba_playoff_bets#bulksave'

  resources :nba_playoff_matchups
  get 'nba_playoff_matchups/:id/winner' => 'nba_playoff_matchups#setwinner'
  post 'nba_playoff_matchups/:id/winner' => 'nba_playoff_matchups#updatewinner'

  resources :nba_teams

  resources :mlb_win_bets
  post '/mlb_win_bets_save' => 'mlb_win_bets#bulksave'
  get '/mlbOverUnders' => 'mlb_win_bets#allusers'
  get '/mlbOverUnderBets' => 'mlb_win_bets#index'

  resources :mlb_wins

  resources :mlb_teams

  resources :users
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get '/editProfile' => 'users#editprofile'
  get '/myGames' => 'users#mygames', :as => 'my_games'
  
  resources :sessions
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => 'sessions#new'

end

app/models/nba_playoff_score.rb
class NbaPlayoffScore < ActiveRecord::Base
  attr_accessible :name, :points, :round

  BONUS_GAMES_ROUND = 5
end

app/controllers/nba_playoff_scores_controller.rb
class NbaPlayoffScoresController < ApplicationController
  # GET /nba_playoff_scores
  # GET /nba_playoff_scores.json
  def index
    @nba_playoff_scores = NbaPlayoffScore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nba_playoff_scores }
    end
  end

  # GET /nba_playoff_scores/1
  # GET /nba_playoff_scores/1.json
  def show
    @nba_playoff_score = NbaPlayoffScore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nba_playoff_score }
    end
  end

  # GET /nba_playoff_scores/new
  # GET /nba_playoff_scores/new.json
  def new
    @nba_playoff_score = NbaPlayoffScore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nba_playoff_score }
    end
  end

  # GET /nba_playoff_scores/1/edit
  def edit
    # TODO confirm logged-in user is admin
    @nba_playoff_score = NbaPlayoffScore.find(params[:id])
  end

  # POST /nba_playoff_scores
  # POST /nba_playoff_scores.json
  def create
    @nba_playoff_score = NbaPlayoffScore.new(params[:nba_playoff_score])

    respond_to do |format|
      if @nba_playoff_score.save
        format.html { redirect_to @nba_playoff_score, notice: 'Nba playoff score was successfully created.' }
        format.json { render json: @nba_playoff_score, status: :created, location: @nba_playoff_score }
      else
        format.html { render action: "new" }
        format.json { render json: @nba_playoff_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nba_playoff_scores/1
  # PUT /nba_playoff_scores/1.json
  def update
    # TODO confirm logged-in user is admin
    @nba_playoff_score = NbaPlayoffScore.find(params[:id])

    respond_to do |format|
      if @nba_playoff_score.update_attributes(params[:nba_playoff_score])
        format.html { redirect_to '/nba_playoff_matchups',
                      notice: 'NBA playoff scoring formula updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nba_playoff_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nba_playoff_scores/1
  # DELETE /nba_playoff_scores/1.json
  def destroy
    # TODO confirm logged-in user is admin
    @nba_playoff_score = NbaPlayoffScore.find(params[:id])
    @nba_playoff_score.destroy

    respond_to do |format|
      format.html { redirect_to '/nba_playoff_matchups',
                    notice: 'NBA playoff scoring formula destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/nba_playoff_scores_helper.rb
module NbaPlayoffScoresHelper
end

app/views/nba_playoff_scores/_form.html.erb
<%= form_for(@nba_playoff_score) do |f| %>
  <% if @nba_playoff_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nba_playoff_score.errors.count, "error") %> prohibited this nba_playoff_score from being saved:</h2>

      <ul>
      <% @nba_playoff_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round %><br />
    <%= f.number_field :round %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nba_playoff_scores/edit.html.erb
<%= navigationBar(NavigationHelper::ADMIN_NBA_PLAYOFF_MATCHUPS_BUTTON) %>

<div class='row-fluid'><div class='span12 center'>

  <h3>Edit Playoff Scoring Formula</h3>

  <%= render 'form' %>

  <%= link_to 'Back', '/nba_playoff_matchups' %>

</div></div>

app/views/nba_playoff_scores/index.html.erb
<h1>Listing nba_playoff_scores</h1>

<table>
  <tr>
    <th>Round</th>
    <th>Points</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nba_playoff_scores.each do |nba_playoff_score| %>
  <tr>
    <td><%= nba_playoff_score.round %></td>
    <td><%= nba_playoff_score.points %></td>
    <td><%= nba_playoff_score.name %></td>
    <td><%= link_to 'Show', nba_playoff_score %></td>
    <td><%= link_to 'Edit', edit_nba_playoff_score_path(nba_playoff_score) %></td>
    <td><%= link_to 'Destroy', nba_playoff_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nba playoff score', new_nba_playoff_score_path %>

app/views/nba_playoff_scores/new.html.erb
<h1>New nba_playoff_score</h1>

<%= render 'form' %>

<%= link_to 'Back', nba_playoff_scores_path %>

app/views/nba_playoff_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Round:</b>
  <%= @nba_playoff_score.round %>
</p>

<p>
  <b>Points:</b>
  <%= @nba_playoff_score.points %>
</p>

<p>
  <b>Name:</b>
  <%= @nba_playoff_score.name %>
</p>


<%= link_to 'Edit', edit_nba_playoff_score_path(@nba_playoff_score) %> |
<%= link_to 'Back', nba_playoff_scores_path %>