config/routes.rb
Games::Application.routes.draw do
  resources :mlb_standings

  resources :nba_playoff_scores

  resources :nba_playoff_bets
  get '/nbaPlayoffs' => 'nba_playoff_bets#allusers'
  get '/nbaPlayoffBets' => 'nba_playoff_bets#index'
  post '/nba_playoff_bets_save' => 'nba_playoff_bets#bulksave'

  resources :nba_playoff_matchups
  get 'nba_playoff_matchups/:id/winner' => 'nba_playoff_matchups#setwinner'
  post 'nba_playoff_matchups/:id/winner' => 'nba_playoff_matchups#updatewinner'

  resources :nba_teams

  resources :mlb_win_bets
  post '/mlb_win_bets_save' => 'mlb_win_bets#bulksave'
  get '/mlbOverUnders' => 'mlb_win_bets#allusers'
  get '/mlbOverUnderBets' => 'mlb_win_bets#index'

  resources :mlb_wins

  resources :mlb_teams

  resources :users
  get 'sign_up' => 'users#new', :as => 'sign_up'
  get '/editProfile' => 'users#editprofile'
  get '/myGames' => 'users#mygames', :as => 'my_games'
  
  resources :sessions
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  root :to => 'sessions#new'

end

app/models/mlb_team.rb
class MlbTeam < ActiveRecord::Base
  attr_accessible :abbreviation, :city, :division, :league, :name
  has_many :mlb_wins
end

app/controllers/mlb_teams_controller.rb
class MlbTeamsController < ApplicationController
  # GET /mlb_teams
  # GET /mlb_teams.json
  def index
    @mlb_teams = MlbTeam.order(:league, :division, :city).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mlb_teams }
    end
  end

  # GET /mlb_teams/1
  # GET /mlb_teams/1.json
  def show
    @mlb_team = MlbTeam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mlb_team }
    end
  end

  # GET /mlb_teams/new
  # GET /mlb_teams/new.json
  def new
    @mlb_team = MlbTeam.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mlb_team }
    end
  end

  # GET /mlb_teams/1/edit
  def edit
    @mlb_team = MlbTeam.find(params[:id])
  end

  # POST /mlb_teams
  # POST /mlb_teams.json
  def create
    @mlb_team = MlbTeam.new(params[:mlb_team])

    respond_to do |format|
      if @mlb_team.save
        format.html { redirect_to @mlb_team, notice: 'Mlb team was successfully created.' }
        format.json { render json: @mlb_team, status: :created, location: @mlb_team }
      else
        format.html { render action: "new" }
        format.json { render json: @mlb_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mlb_teams/1
  # PUT /mlb_teams/1.json
  def update
    @mlb_team = MlbTeam.find(params[:id])

    respond_to do |format|
      if @mlb_team.update_attributes(params[:mlb_team])
        format.html { redirect_to @mlb_team, notice: 'Mlb team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mlb_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mlb_teams/1
  # DELETE /mlb_teams/1.json
  def destroy
    @mlb_team = MlbTeam.find(params[:id])
    @mlb_team.destroy

    respond_to do |format|
      format.html { redirect_to mlb_teams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mlb_teams_helper.rb
module MlbTeamsHelper
end

app/views/mlb_teams/_form.html.erb
<%= form_for(@mlb_team) do |f| %>
  <% if @mlb_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mlb_team.errors.count, "error") %> prohibited this mlb_team from being saved:</h2>

      <ul>
      <% @mlb_team.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :league %><br />
    <%= f.text_field :league %>
  </div>
  <div class="field">
    <%= f.label :division %><br />
    <%= f.text_field :division %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mlb_teams/edit.html.erb
<h1>Editing mlb_team</h1>

<%= render 'form' %>

<%= link_to 'Show', @mlb_team %> |
<%= link_to 'Back', mlb_teams_path %>

app/views/mlb_teams/index.html.erb
<%= navigationBar(NavigationHelper::ADMIN_MLB_TEAMS_BUTTON) %>

<div class='row-fluid'><div class='span12 center'>
<h3>Manage MLB Teams</h3>

<table class='table table-striped table-bordered table-condensed center'>
  <thead><tr>
    <th>City</th>
    <th>Name</th>
    <th>Abbreviation</th>
    <th>League</th>
    <th>Division</th>
    <th></th>
    <th></th>
    <th></th>
  </tr></thead>

<% @mlb_teams.each do |mlb_team| %>
  <tr>
    <td><%= mlb_team.city %></td>
    <td><%= mlb_team.name %></td>
    <td><%= mlb_team.abbreviation %></td>
    <td><%= mlb_team.league %></td>
    <td><%= mlb_team.division %></td>
    <td><%= link_to 'Show', mlb_team %></td>
    <td><%= link_to 'Edit', edit_mlb_team_path(mlb_team) %></td>
    <td><%= link_to 'Destroy', mlb_team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mlb team', new_mlb_team_path, class: 'btn' %>
<br/><br/>
</div></div>

app/views/mlb_teams/new.html.erb
<h1>New mlb_team</h1>

<%= render 'form' %>

<%= link_to 'Back', mlb_teams_path %>

app/views/mlb_teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>City:</b>
  <%= @mlb_team.city %>
</p>

<p>
  <b>Name:</b>
  <%= @mlb_team.name %>
</p>

<p>
  <b>Abbreviation:</b>
  <%= @mlb_team.abbreviation %>
</p>

<p>
  <b>League:</b>
  <%= @mlb_team.league %>
</p>

<p>
  <b>Division:</b>
  <%= @mlb_team.division %>
</p>


<%= link_to 'Edit', edit_mlb_team_path(@mlb_team) %> |
<%= link_to 'Back', mlb_teams_path %>
<br/><br/>
<%= link_to 'New Mlb team', new_mlb_team_path, class: 'btn' %>